### ISSUE TITLE
File and class names should reflect actual service name: Analytics, not Analytic

### ISSUE THREAD

**Issue by ulemanstreaming** [dse-jarvis/4genius#3]
The full name of the service whose API we're covering is IBM Analytics Engine powered by Apache Spark, or Analytics Engine for short. All artifacts in our repo, from variable, function/method, and class names to file names, should reflect that (unless abbreviated to AE or ae).

Specifically,
- Rename the file `analytic_engine_client.py` to `analytics_engine_client.py`
- Rename the class `AnalyticEngineClient` to  `AnalyticsEngineClient`
- Resolve any breakage where these names are referenced

**Comment by Dheeraj-Arremsetty** [comment]
I have fixed this and the code is now in the master branch.
class renamed from AnalyticEngineClient to AnalyticsEngineClient
file renamed from analytic_engine_client.py to analytics_engine_client.py

Also, I have made changes in the test scripts where we import the module.
